import type { Metadata } from "next";
import { LegalPage } from "@/features/legal/legal-page";
import { LEGAL_CONTENT_REVIEW_STATUS } from "@/lib/legal/status";

export const metadata: Metadata = { title: "Privacy | Whale Student Agent" };
export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  void LEGAL_CONTENT_REVIEW_STATUS;
  return (
    <LegalPage
      eyebrow="Privacy"
      title="Privacy at Whale Student Agent"
      summary="This notice explains what information Whale Student Agent handles, why it is used, which outside services are involved, and the controls available to you."
    >
      <section className="panel"><h2>Who operates the service</h2><p>Whale Student Agent is operated by Kim WooJin in the Republic of Korea. Privacy and data questions can be sent to <a className="font-medium text-primary underline underline-offset-4" href="mailto:kth.daniel0525@gmail.com">kth.daniel0525@gmail.com</a>.</p></section>
      <section className="panel"><h2>Account and profile information</h2><p>We process your name, email address, authentication and session records, school, program, year, semester, academic goals, study preferences, and related profile settings. This information is used to sign you in, protect your account, configure your workspace, and personalize study support.</p></section>
      <section className="panel"><h2>Academic and learning information</h2><p>The service stores the courses, assignments, exams, deadlines, completion states, quizzes, answers, grading results, learning topics, mastery estimates, study plans, workflow progress, recommendations, reminders, and notifications that you create or generate. These records support planning, practice, progress tracking, and personalized assistance.</p></section>
      <section className="panel"><h2>Uploaded documents and retrieval</h2><p>PDF, text, and Markdown files you upload are kept in private application storage. The service extracts pages and passages and creates local vector embeddings so it can retrieve relevant material for supported features. Document titles, processing metadata, extracted content, and retrieval references remain connected to your account. Deleting a document removes it from normal retrieval and starts deletion of its stored file.</p></section>
      <section className="panel"><h2>AI processing</h2><p>When you use an AI feature, your request and a limited amount of task-relevant context may be sent to OpenAI. Depending on the task, that context can include selected profile or academic details, relevant passages from documents, recent conversation history or summaries, saved memory, and quiz material needed for semantic grading. Full files are not sent merely because they exist. Passwords, session cookies, service API keys, OAuth tokens, database credentials, and billing records are excluded from AI context. OpenAI requests use the application&apos;s <code>store: false</code> setting.</p></section>
      <section className="panel"><h2>Memory and personalization</h2><p>Whale Student Agent can save explicit preferences and supported observations about learning patterns or successful study strategies. Saved memory is scoped to your account. You can inspect, archive, or delete memory in Settings; archived memory is not used for active personalization but remains stored until you delete it.</p></section>
      <section className="panel"><h2>Operational information</h2><p>The service records limited technical information needed to operate and protect the product, including AI model and token usage, estimated cost, latency, reliability categories, job status, security events, and error metadata. These records are designed not to contain full prompts, uploaded document bodies, passwords, cookies, provider credentials, or raw private AI responses. If product analytics is enabled, it uses allowlisted product events and provides an opt-out control; collection is disabled in the current hosted staging environment.</p></section>
      <section className="panel"><h2>Outside service providers</h2><ul><li><strong>DigitalOcean</strong> hosts the current application, database, and private document storage.</li><li><strong>OpenAI</strong> processes the bounded requests and context needed for AI generation and semantic grading.</li><li><strong>GitHub and GitHub Container Registry</strong> support source automation and application-image delivery; they are not part of the normal runtime path for your academic content.</li></ul><p className="mt-3">Google integrations, Stripe billing, Sentry error delivery, and external product-analytics services are not enabled in the current hosted staging environment. Local document retrieval uses a locally hosted embedding model rather than a hosted embedding API.</p></section>
      <section className="panel"><h2>Your controls</h2><p>You can update profile and academic records, delete uploaded documents, manage saved memory, delete AI conversations, control available product analytics settings, and request permanent account deletion from Settings. Integration controls appear only when an integration is available and connected.</p></section>
      <section className="panel"><h2>Deletion</h2><p>Account deletion requires your current password and an explicit confirmation. It disables account access and starts removal of owned application data and private uploaded files. Records independently maintained by service providers, infrastructure logs, and backup copies may follow separate provider or operator processes. Contact support if you cannot access the in-product controls.</p></section>
      <section className="panel"><h2>AI accuracy</h2><p>AI-generated output may be incomplete or inaccurate. Verify important academic work, deadlines, course requirements, citations, and answers against your course materials and official sources.</p></section>
      <section className="panel"><h2>Contact</h2><p>For privacy questions, account-access issues, or help using data controls, email <a className="font-medium text-primary underline underline-offset-4" href="mailto:kth.daniel0525@gmail.com">kth.daniel0525@gmail.com</a>.</p></section>
    </LegalPage>
  );
}
