export const CONVERSATION_CONFIG = Object.freeze({
  recentMessageCount: 12,
  minimumRecentMessages: 4,
  compressionMessageThreshold: 24,
  compressionTokenThreshold: 6000,
  compressionBatchMessages: 40,
  compressionBatchTokens: 7000,
  historicalRetrievalLimit: 5,
  maximumHistoricalRetrievalLimit: 8,
  maximumMessageCharacters: 12000,
  maximumSummaryTextCharacters: 3000,
  maximumSummaryItemsPerCategory: 12,
  maximumSummarySourcesPerItem: 5,
  totalInputTargetTokens: 16000,
  systemAndRequestReserveTokens: 1800,
  minimumConversationTokens: 1800,
  maximumConversationTokens: 4800,
  agentConversationTokens: {
    tutor: 3600,
    notes: 2800,
    quiz: 3400,
    "study-planner": 4200,
    "academic-manager": 4200,
    career: 4000,
  } as Readonly<Record<string, number>>,
});
