'use client';
import {useRef,useState} from 'react';
import {Braces, ArrowUpRight, Upload, Sparkles, Settings2, Code2, ScanLine, Copy, Check, ShieldCheck, FileCode2, ArrowRight, LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {inspect,reportSchema,type Report} from '@/lib/analysis';
const example=`function findDuplicates(items) {\n  var duplicates = [];\n\n  for (let i = 0; i < items.length; i++) {\n    for (let j = i + 1; j < items.length; j++) {\n      if (items[i] == items[j]) {\n        duplicates.push(items[i]);\n      }\n    }\n  }\n\n  return duplicates;\n}`;
export default function Home(){
 const [code,setCode]=useState(example),[filename,setFilename]=useState('duplicates.js'),[report,setReport]=useState<Report|null>(null),[snapshot,setSnapshot]=useState(''),[mode,setMode]=useState(''),[key,setKey]=useState(''),[model,setModel]=useState(''),[settings,setSettings]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);const file=useRef<HTMLInputElement>(null);const [connecting,setConnecting]=useState(false),[connectionMessage,setConnectionMessage]=useState('');
 async function upload(f?:File){if(!f)return;if(f.size>80000){setError('80KB 이하의 코드 파일을 선택하세요.');return;}try{const text=await f.text();if(text.includes('\0')||text.length>40000){setError('텍스트 코드 파일만 지원하며 최대 40,000자입니다.');return;}setCode(text);setFilename(f.name);setError('');}catch{setError('파일을 읽지 못했습니다.');}}
 async function post(path:string,body:unknown){
 const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(180000)});
 if(!res.headers.get('content-type')?.includes('application/json'))throw Error('로그인이 만료되었거나 서버에 연결하지 못했습니다. 앱을 새로고침한 뒤 API 키를 다시 입력하세요.');
 const data=await res.json() as {error?:string,model?:string,message?:string};if(!res.ok)throw Error(data.error||'서버 요청에 실패했습니다.');return data;
 }
 function keyInput(value:string){setKey(value);setModel('');setConnectionMessage('');}
 async function connect(){setConnecting(true);setConnectionMessage('');try{if(/^https?:|aistudio\.google|generativelanguage\.google/i.test(key.trim()))throw Error('웹주소가 아닌 발급받은 비밀 API 키를 입력하세요. API 주소는 이미 연결되어 있습니다.');const data=await post('/api/connection',{key});setModel(data.model||'');setConnectionMessage(data.message||'키 인증 완료');}catch(e){setConnectionMessage(e instanceof Error?e.message:'연결에 실패했습니다.');}finally{setConnecting(false);}}
 async function analyze(){setBusy(true);setError('');const source=code;try{if(key.trim()){if(/^https?:|aistudio\.google|generativelanguage\.google/i.test(key.trim()))throw Error('웹주소가 입력되었습니다. AI 연결에서 Google AI Studio가 발급한 비밀 API 키로 바꿔 주세요.');const data=await post('/api/analyze',{code:source,key:key.trim(),model});setReport(reportSchema.parse(data));setModel(data.model||model);setMode('Gemini AI');}else{setReport(inspect(source));setMode('기본 규칙 검사');}setSnapshot(source);}catch(e){setError(e instanceof Error?(e.name==='TimeoutError'?'분석 시간이 초과되었습니다. 코드를 줄여 다시 시도하세요.':e.message):'분석하지 못했습니다.');}finally{setBusy(false);}}

 return <div className="app-shell"><header><a className="brand" href="/"><span className="brand-icon"><Braces size={23}/></span>codechoice<span className="brand-ai">ai</span></a><span className="header-caption">더 나은 코드를 만드는 선택</span><button className="quiet" onClick={()=>setSettings(true)}><Settings2 size={16}/> AI 연결 <span className="connection">{model?'키 인증됨':key?'확인 필요':'설정 필요'}</span></button></header>
 <main><div className="intro"><div><div className="eyebrow">YOUR CODE, A CLEARER PERSPECTIVE</div><h1>좋은 코드의 시작,<br className="mobile-break"/> 명확한 코드 리뷰.</h1><p>코드를 올리고 가독성부터 성능, 개선 방향까지 한눈에 확인하세요.</p></div><span className="workspace-label"><ScanLine size={16}/> 코드 분석 워크스페이스</span></div>
 <div className="workspace"><section className="editor-panel"><div className="panel-heading"><h2><Code2 size={19}/> 소스 코드</h2><button className="text-button" disabled={busy} onClick={()=>{setCode(example);setFilename('duplicates.js');setError('');}}>예제 불러오기 <ArrowUpRight size={14}/></button></div><div className="file-bar"><span><FileCode2 size={16}/>{filename}</span><span>UTF-8</span></div><div className="code-editor"><div className="line-numbers" aria-hidden="true">{code.split('\n').map((_,i)=><div key={i}>{i+1}</div>)}</div><textarea aria-label="분석할 소스 코드" spellCheck={false} onScroll={e=>{const gutter=e.currentTarget.previousElementSibling;if(gutter)gutter.scrollTop=e.currentTarget.scrollTop;}} value={code} disabled={busy} onChange={e=>setCode(e.target.value)} maxLength={40000}/></div><div className="editor-meta"><span>{code.split('\n').length} lines</span><span>{code.length.toLocaleString()} / 40,000자</span></div><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(e.dataTransfer.files[0]);}}><Upload size={21}/><div><button disabled={busy} onClick={()=>file.current?.click()}>파일 선택</button> 또는 여기에 끌어다 놓으세요<p>JS, TS, Python, Java, C++ 등 텍스트 코드 · 최대 80KB</p></div><input ref={file} type="file" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></div><div className="run-area"><p><ShieldCheck size={15}/>{key?'분석 시 코드가 Google Gemini로 전송됩니다.':'기본 검사는 브라우저 안에서만 처리됩니다.'}</p><button className="primary" disabled={busy||!code.trim()} onClick={analyze}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy?'코드 분석 중…':key?'Gemini로 분석하기':'코드 분석하기'} {!busy&&<ArrowRight size={18}/>}</button></div></section>
 <section className="result-panel" aria-live="polite"><div className="panel-heading"><h2><ScanLine size={19}/> 분석 결과</h2><span className="result-badge">{report?mode:'READY TO REVIEW'}</span></div>{error&&<div className="error" role="alert">{error}</div>}{report&&snapshot!==code&&<div className="notice">코드가 변경되었습니다. 다시 분석해 결과를 업데이트하세요.</div>}{!report?<div className="empty-result"><div className="orbit"><Braces size={38}/><span><Sparkles size={17}/></span></div><h3>코드 속 가능성을 발견하세요</h3><p>왼쪽에 코드를 붙여 넣거나 파일을 업로드한 뒤<br/>분석 버튼을 눌러 시작하세요.</p><div className="preview-checks">{['가독성 · 읽기 쉬운 구조','유지보수성 · 수정과 확장','시간 복잡도 · 성능과 근거','문제점 · 구체적인 해결책'].map((s,i)=><div key={s}><span>0{i+1}</span>{s}<Check size={15}/></div>)}</div><small>API 키 없이 기본 검사를 먼저 사용해 보세요.</small></div>:<div className="report"><div className="summary"><span className="eyebrow">REVIEW OVERVIEW</span><h3>{report.issues.length?'더 나아질 수 있는 코드입니다.':'코드 검토를 완료했습니다.'}</h3><p>{report.summary}</p></div><div className="metrics"><div><span>가독성</span><strong>{report.readability}<small>/100</small></strong><div className="meter"><i style={{width:`${report.readability}%`}}/></div></div><div><span>유지보수성</span><strong>{report.maintainability}<small>/100</small></strong><div className="meter"><i style={{width:`${report.maintainability}%`}}/></div></div><div><span>시간 복잡도</span><strong className="complexity">{report.complexity}</strong><small>정적 분석 추정</small></div></div><p className="score-note">점수는 {mode==='Gemini AI'?'AI의 주관적 평가':'단순 규칙 기반 참고값'}입니다.</p><Tabs defaultValue="issues"><TabsList className="result-tabs"><TabsTrigger value="issues">문제점 {report.issues.length}</TabsTrigger><TabsTrigger value="complexity">복잡도</TabsTrigger><TabsTrigger value="improved">개선 코드</TabsTrigger></TabsList><TabsContent value="issues"><div className="issues">{report.issues.length?report.issues.map((issue,i)=><article key={i}><div><span className={`severity ${issue.severity}`}>{({high:'높음',medium:'중간',low:'낮음'})[issue.severity]}</span><span className="line-tag">L{issue.line}</span></div><h4>{issue.title}</h4><p>{issue.description}</p><div className="solution"><ArrowRight size={15}/><p>{issue.solution}</p></div></article>):<p className="detail">발견된 문제점이 없습니다. 경계값 테스트와 실제 실행 검증도 진행하세요.</p>}</div></TabsContent><TabsContent value="complexity"><div className="detail"><h4>분석 근거와 가정</h4><p>{report.complexityReason}</p><p>실제 실행 시간을 측정한 결과가 아닙니다.</p></div></TabsContent><TabsContent value="improved"><div className="detail"><p>{report.improvementNote}</p>{report.improvedCode&&<><button className="quiet" onClick={async()=>{try{await navigator.clipboard.writeText(report.improvedCode);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('복사하지 못했습니다. 코드를 직접 선택해 복사하세요.');}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'복사됨':'개선 코드 복사'}</button><pre>{report.improvedCode}</pre></>}</div></TabsContent></Tabs></div>}</section></div>
 <footer><span><Braces size={15}/> codechoiceai</span><p>코드를 실행하지 않습니다. AI의 제안은 적용 전 테스트하세요.</p><button onClick={()=>setSettings(true)}>Powered by your choice <ArrowUpRight size={14}/></button></footer></main>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogTitle>Gemini AI 연결</DialogTitle><DialogDescription>웹주소가 아니라 Google AI Studio에서 발급받은 비밀 API 키가 필요합니다. API 주소는 앱에 이미 설정되어 있습니다.</DialogDescription><a className="key-link" href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Google AI Studio에서 API 키 발급 <ArrowUpRight size={16}/></a><label>Gemini API 키 (웹주소 아님)<input type="password" autoComplete="off" placeholder="발급받은 키를 붙여 넣으세요" value={key} disabled={connecting||busy} onChange={e=>keyInput(e.target.value)}/></label><button className="primary" disabled={connecting||busy||!key.trim()} onClick={connect}>{connecting?'Google 연결 확인 중…':'연결 확인 · 사용 가능한 모델 찾기'}</button>{connectionMessage&&<p role="status" className="settings-note">{connectionMessage}</p>}{model&&<p className="settings-note">자동 선택 모델: <strong>{model}</strong></p>}<p className="settings-note">키는 현재 페이지의 메모리에만 유지됩니다. 분석할 때 서버를 거쳐 Google로 전송하며 저장하지 않습니다. 새로고침하면 키가 삭제됩니다. Google 계정의 사용 한도·요금이 적용됩니다.</p><div className="settings-actions"><button className="quiet" disabled={connecting||busy} onClick={()=>keyInput('')}>키 지우기</button><button className="primary" onClick={()=>setSettings(false)}>설정 완료</button></div></DialogContent></Dialog>
 </div>;
}
