import { z } from 'zod';
export const reportSchema = z.object({summary:z.string(),readability:z.number().min(0).max(100),maintainability:z.number().min(0).max(100),complexity:z.string(),complexityReason:z.string(),issues:z.array(z.object({title:z.string(),severity:z.enum(['high','medium','low']),line:z.number().int().min(1),description:z.string(),solution:z.string()})).max(30),improvedCode:z.string(),improvementNote:z.string()});
export type Report = z.infer<typeof reportSchema>;
export function inspect(code:string):Report {
 const lines=code.split('\n'); const issues:Report['issues']=[];
 lines.forEach((s,i)=>{if(s.length>100)issues.push({title:'긴 코드 줄',severity:'low',line:i+1,description:'한 줄에 정보가 많아 읽기 어려울 수 있습니다.',solution:'중간 변수 또는 보조 함수로 표현식을 나누세요.'});if(/\beval\s*\(/.test(s))issues.push({title:'동적 코드 실행',severity:'high',line:i+1,description:'외부 입력이 전달되면 임의 코드 실행으로 이어질 수 있습니다.',solution:'JSON 파싱이나 명시적인 함수 매핑을 사용하세요.'});if(/\b(var)\s+/.test(s))issues.push({title:'변수 범위가 불명확함',severity:'low',line:i+1,description:'var의 함수 범위와 재선언은 변경 추적을 어렵게 합니다.',solution:'재할당 여부를 확인한 후 const 또는 let으로 바꾸세요.'});if(/==(?!=)/.test(s)&&!/[!=]==/.test(s))issues.push({title:'비교 의미 확인',severity:'medium',line:i+1,description:'JavaScript에서는 == 비교가 암묵적인 형 변환을 수행합니다. 다른 언어에는 해당하지 않을 수 있습니다.',solution:'JavaScript/TypeScript라면 의도에 맞는지 확인하고 === 사용을 검토하세요.'});});
 const loops=(code.match(/\b(for|while)\b/g)||[]).length;
 return {summary:issues.length?`${issues.length}개의 검토 후보를 찾았습니다. 기본 검사는 문법 패턴을 확인하며 실제 오류를 확정하지 않습니다.`:'기본 규칙에서 검토 후보를 찾지 못했습니다. 코드의 정확성을 보장하는 결과는 아닙니다.',readability:Math.max(20,100-issues.length*8),maintainability:Math.max(20,100-issues.filter(x=>x.severity!=='low').length*15-(lines.length>80?15:0)),complexity:'판단 보류',complexityReason:`반복문 키워드 ${loops}개를 발견했습니다. 문자열·주석도 포함될 수 있으며, 중첩·입력 크기·호출 함수를 검증하지 않아 Big-O를 확정할 수 없습니다. Gemini 분석으로 근거를 확인하세요.`,issues:issues.slice(0,30),improvedCode:'',improvementNote:'자동 변경으로 동작을 바꾸지 않도록 기본 검사는 개선 방향만 제공합니다. Gemini를 연결하면 개선 코드도 제안합니다.'};
}
